language: objective-c
osx_image: xcode7

script:
- xctool -workspace sandbox.xcworkspace -scheme sandbox-debug ONLY_ACTIVE_ARCH=NO

before_install:
- brew uninstall xctool; 
- brew install xctool --HEAD;
- brew install homebrew/versions/glfw3;
- brew install libusb;